sudo: required
services:
  - docker

before_install:
  - docker build -t loki194/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run loki194/react-test npm test -- --coverage

after_success:
  - docker build -t loki194/multi-client ./client
  - docker build -t loki194/multi-nginx ./nginx
  - docker build -t loki194/multi-server ./server
  - docker build -t loki194/multi-worker ./worker

  # take these images and push to the docker-hub
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push loki194/multi-client
  - docker push loki194/multi-nginx
  - docker push loki194/multi-server
  - docker push loki194/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-327326504583
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY